export { default as Navbar } from './Navbar'
export { default as HomePage } from './HomePage'
export { default as ExchangesPage } from './ExchangesPage'
export { default as CryptocurrenciesPage } from './CryptocurrenciesPage'
export { default as CryptoDetailsPage } from './CryptoDetailsPage'
export { default as NewsPage } from './NewsPage'
